---
- name: Check if website is accessible
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: website_url
      prompt: "Enter the website URL to check (e.g., https://example.com)"
      private: no  # Show input while typing (not hidden like a password)

  tasks:
    - name: Check website status with URI module
      uri:
        url: "{{ website_url }}"
        method: GET
        status_code: 200
        return_content: no
      register: website_check
      failed_when: website_check.status != 200

    - name: Print website response info
      debug:
        msg: >
          ✅ Website {{ website_url }} is reachable
          with status: {{ website_check.status }}.
