---
- name: Update and upgrade packages on Ubuntu
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # in seconds (1 hour)

    - name: Upgrade all packages to latest
      apt:
        upgrade: dist
